= Vert.x CouchDB Client
:toc: left
:lang: $lang
:$lang: $lang

The Vert.x CouchDB Client is a convenience wrapper around the https://vertx.io/docs/vertx-web-client/java/[Vert.x Web Client] allowing applications to interact with an https://couchdb.apache.org/[Apache CouchDB] (or compatible) instance, for CRUD operations, administrative tasks and database design. CouchDB is a great match for persisting data in a Vert.x application as it natively handles JSON documents.

== Features

* Completely non-blocking
* Custom codec to support fast serialization to/from Vert.x JSON
* Supports a majority of the configuration options from the vert.x Web Client

This client is based on the
https://github.com/vert-x3/vertx-web/[vert.x Web Client].

== Using Vert.x CouchDB Client

To use this project, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-couchdb-client</artifactId>
  <version>${vertx.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-couchdb-client:${vertx.version}'
----


== Creating a client

[source,$lang]
----
{@link examples.CouchDbClientExample.java}
----

== Authentication

Authentication is provided by the Vert.x web client, so you will use `Credentials` fit for purpose

== CRUD operations

== security

== Design Tasks

== Replication

== CouchDB configuration

== Change listener
